"""add_user_prefs

Revision ID: 4c2a4bcac25a
Revises: 273b8c746f0b
Create Date: 2026-07-13 22:59:48.202151
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c2a4bcac25a'
down_revision: Union[str, None] = '273b8c746f0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('theme', sa.String(length=10), server_default='dark', nullable=False))
    op.add_column('users', sa.Column('lang', sa.String(length=10), server_default='zh', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'lang')
    op.drop_column('users', 'theme')
    # ### end Alembic commands ###
