"""add_user_file_uid

Revision ID: 8ca19dcee7b2
Revises: 4c2a4bcac25a
Create Date: 2026-07-14 00:18:36.214839
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ca19dcee7b2'
down_revision: Union[str, None] = '4c2a4bcac25a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('file_uid', sa.String(length=36), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'file_uid')
    # ### end Alembic commands ###
